## ndarray

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# 生成3层嵌套数组
c = np.array([1,2,3,4,5],ndmin=3)
print(c)

[[[1 2 3 4 5]]]


In [5]:
# 设置dtype数组元素的数据类型
d = np.array([[1,2,3],[1.23,2.34,4.56]],dtype=np.float64)
d

array([[1.  , 2.  , 3.  ],
       [1.23, 2.34, 4.56]])

## dtype

In [6]:
import numpy as np

In [7]:
# 标量
dt0 = np.dtype(np.int32)
dt0

dtype('int32')

In [8]:
#  int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt1 = np.dtype('i8')
dt1

dtype('int64')

In [10]:
# 小端法存储数据
dt2 = np.dtype('<i4')
print(dt2)
dt3 = np.dtype([('name','S10'),('考试合格',np.bool_),('成绩',np.int8)])
print(dt3)
a1 = np.array([('jack',True,80),('rose',False,56),('sandra',True,95)], dtype = dt3)
print(a1)

int32
[('name', 'S10'), ('考试合格', '?'), ('成绩', 'i1')]
[(b'jack',  True, 80) (b'rose', False, 56) (b'sandra',  True, 95)]


In [11]:
'''
每个内建类型都有一个唯一定义它的字符代码
字符    对应类型
b       布尔型 
i       (有符号) 整型 
u       无符号整型 integer 
f       浮点型 
c       复数浮点型 
m       timedelta（时间间隔） 
M       datetime（日期时间） 
O       (Python) 对象 
S,a    (byte-)字符串 
U       Unicode 
V       原始数据 (void) 
'''

'\n每个内建类型都有一个唯一定义它的字符代码\n字符    对应类型\nb       布尔型 \ni       (有符号) 整型 \nu       无符号整型 integer \nf       浮点型 \nc       复数浮点型 \nm       timedelta（时间间隔） \nM       datetime（日期时间） \nO       (Python) 对象 \nS,a    (byte-)字符串 \nU       Unicode \nV       原始数据 (void) \n'

In [13]:
#大小端内存存储演示
dt_a = np.array([1,2,3])
print('小端法存储：')
print(dt_a.view(np.uint8))
dt_a.newbyteorder().byteswap(inplace=True)
print('大端法存储：')
print(dt_a.view(np.uint8))

小端法存储：
[1 0 0 0 2 0 0 0 3 0 0 0]
大端法存储：
[0 0 0 1 0 0 0 2 0 0 0 3]


## 03_ndarrayAttr

In [19]:
import numpy as np

three_x1 = np.arange(24) # 创建等差数组
print(f'a数组维度={str(three_x1.ndim)}')
print('-----------------------------------------------------')
# 现在调整其大小,reshape的3个参数的乘积等于原先一维数组的长度
three_x2 = three_x1.reshape(2,6,2)
print(three_x2.ndim)
print('-----------------------------------------------------')

# 数组形状
print(three_x1.shape)
print(three_x2.shape)

print('-----------------------------------------------------')
#将数组调整为3行2列
three_x3 = np.array([[1,2,3],[4,5,6]])
three_x3.shape = (3,2)
print(three_x3)
print('-----------------------------------------------------')

#一个元素类型为float64的数组itemsize属性值为8(float64占用64个bits,每个字节长度为8，
# 所以64/8,占用8个字节）
# 数组的 dtype 为 int8（一个字节）
three_x4 = np.array([1,2,3,4,5],dtype=np.int8)
print('e数组占用'+str(three_x4.itemsize)+'个8字节') # e数组占用1个8字节
print('-----------------------------------------------------')
# 数组的 dtype 现在为 float64（八个字节）

three_x5 = np.array([1,2,3,4,5],dtype=np.float64)
print('f数组占用'+str(three_x5.itemsize)+'个8字节') # f数组占用8个8字节
print('-----------------------------------------------------')
three_x6 = np.array([1,2,3,4,5])
print(three_x6.flags) # 返回 ndarray 对象的内存信息

# C_CONTIGUOUS : True      #数据是在一个单一的C风格的连续段中
# F_CONTIGUOUS : True      #数据是在一个单一的Fortran风格的连续段中
# OWNDATA : True           #数组拥有它所使用的内存或从另一个对象中借用它
# WRITEABLE : True         #数据区域可以被写入，将该值设置为 False，则数据为只读
# ALIGNED : True           #数据和所有元素都适当地对齐到硬件上
# WRITEBACKIFCOPY : False  #此数组是其他数组的副本
# UPDATEIFCOPY : False     #这个数组是其它数组的一个副本，当这个数组被释放时，原数组的内容将被更新

a数组维度=1
-----------------------------------------------------
3
-----------------------------------------------------
(24,)
(2, 6, 2)
-----------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
-----------------------------------------------------
e数组占用1个8字节
-----------------------------------------------------
f数组占用8个8字节
-----------------------------------------------------
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 04_ndarrayCreate

In [14]:
import numpy as np

In [15]:
# numpy.empty创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组
four_x1 = np.empty([3,2],dtype=int)
#numpy.zeros创建指定大小的数组，数组元素以0来填充
# 默认为浮点数
four_x2 = np.zeros(5)

# 设置类型为整数
four_x3 = np.zeros((5,),dtype=np.int32)

# 自定义类型
four_x4 =  np.zeros((2,2),dtype=[('x','i4'),('y','i4')])

#numpy.ones创建指定形状的数组,数组元素以1来填充
# 默认为浮点数
four_x5 = np.ones(5)
# 自定义类型
four_x6 = np.ones([2,2],dtype=int)
print(four_x1)
print(four_x2)
print(four_x3)
print(four_x4)
print(four_x5)
print(four_x6)

[[749441328       399]
 [        0         0]
 [   131074         0]]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## 05_ndarrayExistCreate

In [21]:
import numpy as np

# python容器对象转换成numpy数组
five_x1 = [1,2,3,4,5]
five_x2 = (1,2,3,4,5)

#元组列表转换为ndarray
print(np.asarray(five_x1))
print(np.asarray(five_x2))


#numpy.fromiter从迭代对象中建立ndarray对象，返回一维数组
# 使用 range 函数创建列表对象

list1 = range(5)
it = iter(list1)
five_x3 = np.fromiter(it,dtype=float)
print(five_x3)

[1 2 3 4 5]
[1 2 3 4 5]
[0. 1. 2. 3. 4.]


## 06_ndarrayValueRangeCreate

In [22]:
#arange函数创建数值范围并返回 ndarray 对象
six_x1 = np.arange(5)
six_x1

array([0, 1, 2, 3, 4])

In [23]:
six_x2 = np.arange(6,dtype=float)
six_x2

array([0., 1., 2., 3., 4., 5.])

In [25]:
#设置起始值、终止值和步长
six_x3 = np.arange(1,10,1)
six_x3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#numpy.linspace函数创建一个一维数组，数组是一个等差数列
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [27]:
np.linspace(1,1,6)

array([1., 1., 1., 1., 1., 1.])

In [28]:
#endpoint设为false不包含终止值
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [30]:
np.linspace(10,20,5,endpoint=False)

array([10., 12., 14., 16., 18.])

In [31]:
#设置显示间距
np.linspace(1,10,10,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [32]:
#numpy.logspace创建等比数列
np.logspace(0,9,10,base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

## 07_ndarraySlice

In [34]:
seven_1 = np.arange(10)
seven_2 = slice(2,7,2) # # 从索引2开始到索引7停止,间隔为2

print(seven_1,seven_2)
print(seven_1[seven_2])


[0 1 2 3 4 5 6 7 8 9] slice(2, 7, 2)
[2 4 6]


In [35]:
#也可以通过冒号分隔切片参数start:stop:step来进行切片操作
seven_1[2:7:2]

array([2, 4, 6])

In [36]:
# 冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，
# 如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

seven_1[5]

5

In [37]:
seven_1[6:]

array([6, 7, 8, 9])

In [40]:
np.array([[1,2,3],[3,4,5],[4,5,6]])[1:]

array([[3, 4, 5],
       [4, 5, 6]])

In [ ]:
# 切片还可以包括省略号…,来使选择元组的长度与数组的维度相同
# 如果在行位置使用省略号，它将返回包含行中元素的ndarray

In [41]:
seven = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [43]:
seven[...,1] #第2列元素

array([2, 4, 5])

In [44]:
seven[1,...] #第2行元素

array([3, 4, 5])

In [45]:
seven[...,1:] #第2列及剩下的所有元素

array([[2, 3],
       [4, 5],
       [5, 6]])

## 08_ndarrayIndex

In [50]:
import numpy as np

In [52]:
eight1 = np.array([[1,2],[3,4],[5,6]])
# 获取数组中(0,0),(1,1)和(2,0)位置处的元素
eight1[[0,1,2],[[0,1,0]]]

array([[1, 4, 5]])

In [53]:
eight2 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])

eight2[rows,cols]

array([[ 0,  2],
       [ 9, 11]])

In [54]:
#切片:或...与索引数组组合
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a数组:')
print(a)
b = a[1:,1:]
print('b数组:')
print(b)
c = a[1:,[1,2]] #[1,2]取第2列和第3列
print('c数组:')
print(c)
d = a[...,1:]
print('d数组:')
print(d)

a数组:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b数组:
[[5 6]
 [8 9]]
c数组:
[[5 6]
 [8 9]]
d数组:
[[2 3]
 [5 6]
 [8 9]]


In [55]:
#布尔索引通过布尔运算获取符合指定条件的元素的数组
eight3 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
eight3[eight3 > 5]

array([ 6,  7,  8,  9, 10, 11])

In [56]:
eight4 = np.array([np.nan,1,2,np.nan,3,4,5])
# 非空过滤数组
eight4[~np.isnan(eight4)]

array([1., 2., 3., 4., 5.])

In [57]:
# 过滤复数数组
eight5 = np.array([1,2+6j,5,3.5+5j])
eight5[np.iscomplex(eight5)]

array([2. +6.j, 3.5+5.j])

In [62]:
# 花式索引指的是利用整数数组进行索引。
# 花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。
# 对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；
# 如果目标是二维数组，那么就是对应下标的行。
# 花式索引跟切片不一样，它总是将数据复制到新数组中。
np.arange(32).reshape(8,4)[[4,2,1,7]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [28, 29, 30, 31]])

In [64]:
# 传入多个索引数组(要使用np.ix_)
print(np.arange(32).reshape(8,4))
np.arange(32).reshape(8,4)[np.ix_([1,5,7,2],[0,3,1,2])]
# 1,0  1,3   1,1   1,2
# 5,0  5,3   5,1   5,2
# ...
# ...

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 09_ndarrayBroadcast

In [46]:
# 广播机制
nine1 = np.array([1,2,3,4])
nine2 = np.array([10,20,30,40])
nine1 * nine2

array([ 10,  40,  90, 160])

In [47]:
#当运算中的 2个数组的形状不同时，numpy将自动触发广播机制
nine3 = np.array([[ 0, 0, 0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])
              
              
nine4 = np.array([1,2,3])
nine3 * nine4

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [48]:
# tile()函数将原矩阵横向、纵向地复制
np.tile(nine4,(4,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
np.tile(nine3,(2,3))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30]])

## 10_ndarrayNditer

In [ ]:
import numpy as np

a1 = np.arange(6).reshape(2,3)
print('a1数组是:')
print(a1)
print('迭代元素:')
for x in np.nditer(a1):print(x,end=',')
print('\n')
print('-----------------------------------------------------')
'''
a1数组是:
[[0 1 2]
 [3 4 5]]
迭代元素:
0,1,2,3,4,5,
'''

a2 = np.arange(0,60,5)
a2 = a2.reshape(3,4)
print('a2数组:')
print(a2)
a3 = a2.T
print('a2转置:')
print(a3)
print('以C风格顺序排序：')
c = a3.copy(order='C')
print(c)
for x in np.nditer(c):print(x,end=',')
print('\n')
print('以Fortran风格顺序排序：')
c = a3.copy(order='F')
print(c)
for x in np.nditer(c):print (x,end=',')
print('\n')
print('强制nditer对象使用C顺序')
for x in np.nditer(c,order='C'):print(x,end=',')
print('\n')
print('强制nditer对象使用F顺序')
for x in np.nditer(c,order='F'):print(x,end=',')
print('\n')
print('-----------------------------------------------------')

'''
nditer 对象有另一个可选参数 op_flags。 
默认情况下nditer将视待迭代遍历的数组为只读对象(read-only)，
为了在遍历数组的同时，实现对数组元素值得修改，必须指定read-write或者write-only的模式。
'''
print('a2数组:')
print(a2)
a3=a2
for x in np.nditer(a3,op_flags=['readwrite']):
    x[...]=2*x
print('修改后数组:')
print(a3)
print('-----------------------------------------------------')

'''
nditer类的构造器拥有flags参数
参数            描述
c_index         可以跟踪C顺序(横向)的索引 
f_index         可以跟踪Fortran顺序(纵向)的索引 
multi-index     每次迭代可以跟踪一种索引类型 
external_loop   给出的值是具有多个值的一维数组，而不是零维数组 
'''
a4 = np.arange(0,60,5)
a4 = a4.reshape(3,4)
print('a4原始数组:')
print(a4)
print('修改后的多值一维数组:')
for x in np.nditer(a4,flags=['external_loop'],order='F'):print(x,end=',')
print('\n')
print('-----------------------------------------------------')

#如果两个数组是可广播的，nditer组合对象能够同时迭代它们
print('第一个数组:')
print(a4)
print('第二个数组:')
b = np.array([1,2,3,4],dtype=int)
print(b)
print('修改后的数组为：')
for x,y in np.nditer([a4,b]):print("%d-%d"%(x,y),end=',')
'''
第一个数组:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
第二个数组:
[1 2 3 4]
修改后的数组为：
0-1,5-2,10-3,15-4,20-1,25-2,30-3,35-4,40-1,45-2,50-3,55-4,
'''

## 11_ndarrayModify

In [ ]:
import numpy as np

'''
numpy.reshape 函数可以在不改变数据的条件下修改形状，格式numpy.reshape(arr, newshape, order='C') 
arr:要修改形状的数组
newshape:整数或者整数数组，新的形状应当兼容原有形状
order:'C'按行，'F'按列，'A'原顺序，'k'元素在内存中的出现顺序
'''
a = np.arange(8)
print('原始数组:')
print(a)
b = a.reshape(4, 2)
print('修改后数组:')
print(b)
'''
原始数组:
[0 1 2 3 4 5 6 7]
修改后数组:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
'''
print('-----------------------------------------------------')

#numpy.ndarray.flat数组元素迭代器
a = np.arange(9).reshape(3, 3)
print('原始数组:')
for row in a:print(row)
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print('迭代后的数组：')
for element in a.flat:print(element)
'''
原始数组:
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8
'''
print('-----------------------------------------------------')

'''
numpy.ndarray.flatten返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ndarray.flatten(order='C')
order:'C'按行，'F'按列，'A'原顺序，'k'元素在内存中的出现顺序
'''
a = np.arange(8).reshape(2,4)
print('原数组:')
print(a)
# 默认按行
print('展开的数组:')
a1=a.flatten()
print(a1)
print('以F风格顺序展开数组:')
a2=a.flatten(order='F')
print(a2)
print('-----------------------------------------------------')

'''
numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图，修改会影响原始数组
numpy.ravel(a,order='C')
'''
a = np.arange(8).reshape(2,4)
print('原数组：')
print(a)
print('调用 ravel 函数之后：')
a3=a.ravel()
print(a3)
print('以F风格顺序调用ravel函数之后：')
a4=a.ravel(order='F')
print(a4)


In [ ]:
import numpy as np

'''
numpy.transpose函数用于对换数组的维度
numpy.transpose(arr, axes)
axes：整数列表对应维度，通常所有维度都会对换
'''
a = np.arange(12).reshape(3,4)
print('原数组:')
print(a)
print('对换数组:')
print(np.transpose(a)) #等同于a.T
print('-----------------------------------------------------')

'''
numpy.rollaxis函数向后滚动特定的轴到一个特定位置
numpy.rollaxis(arr, axis, start)
axis：要向后滚动的轴，其它轴的相对位置不会改变
start：默认为零，表示完整的滚动。会滚动到特定位置
'''
a = np.arange(27).reshape(3,3,3)
print('原数组:')
print(a)
#多个二维数组的列数据转为行数据
print('调用rollaxis函数将轴2滚动到轴0宽度到深度:')
print(np.rollaxis(a, 2))
#单个二维数组自身行列数据置换
print('调用rollaxis函数将轴0滚动到轴1宽度到高度:')
print(np.rollaxis(a, 2, 1))
print('-----------------------------------------------------')
'''
原数组:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
调用rollaxis函数将轴2滚动到轴0宽度到深度:
[[[ 0  3  6]
  [ 9 12 15]
  [18 21 24]]

 [[ 1  4  7]
  [10 13 16]
  [19 22 25]]

 [[ 2  5  8]
  [11 14 17]
  [20 23 26]]]
调用rollaxis函数将轴0滚动到轴1宽度到高度:
[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]

 [[18 21 24]
  [19 22 25]
  [20 23 26]]]
'''

'''
numpy.swapaxes函数用于交换数组的两个轴
numpy.swapaxes(arr, axis1, axis2)
axis1：对应第一个轴的整数
axis2：对应第二个轴的整数
'''
a = np.arange(27).reshape(3,3,3)
print('原数组:')
print(a)
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
print('调用swapaxes函数数组:')
print(np.swapaxes(a, 2, 0))
'''
原数组:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

调用swapaxes函数数组:
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]
'''

In [ ]:
import numpy as np

x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
# 对y广播x
b = np.broadcast(x,y)
# 它拥有iterator属性基于自身组件的迭代器元组
print('对y广播x:')
r,c = b.iters
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print('-----------------------------------------------------')
'''
对y广播x:
1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6
'''

# shape属性返回广播对象形状
print('广播对象形状:')
print(b.shape)
print('-----------------------------------------------------')
'''
广播对象的形状：
(3, 3)
'''

# 手动使用broadcast将x与y相加
b = np.broadcast(x,y)
#empty创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组
c1 = np.empty(b.shape) # 和b一样3X3
print('手动使用broadcast将x与y相加:')
'''
[[4 5 6]                   [[5 6 7]
 [4 5 6]   +  [1],[2],[3] = [6 7 8]
 [4 5 6]]                   [7 8 9]]
'''
c1.flat = [u + v for (u, v) in b]
print('调用 flat 函数：')
print(c1)
#获得和NumPy内建的广播支持相同的结果
#更简化的写法
print('x与y的和:')
c2=x+y
print(c2)
print('-----------------------------------------------------')

#numpy.broadcast_to函数将数组广播到新形状。
a = np.arange(3)
print('原数组:')
print(a)
print('调用 broadcast_to 函数之后:')
#第二个参数必须是原数组的对等长度，从而形成正方形矩阵，否则无效果
print(np.broadcast_to(a,(3,3)))
print('-----------------------------------------------------')
'''
原数组:
[0 1 2]
调用 broadcast_to 函数之后:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
'''

'''
numpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状
numpy.expand_dims(arr, axis)
axis：新轴插入的位置
'''
x = np.array(([1,2],[3,4]))
print('数组x:')
print(x)
'''
数组x:
[[1 2]
 [3 4]]
'''
y = np.expand_dims(x, axis=0)
print('数组y:')
print(y)
'''
插入新轴后数组y:
[[[1 2]
  [3 4]]]
'''
print('数组x和y的形状:')
print(x.shape, y.shape)
'''
x.shape (2, 2)
y.shape (1, 2, 2) #多了一个刚插入的轴
'''
# 在位置1插入轴
y = np.expand_dims(x, axis=1)
print('在位置 1 插入轴之后的数组 y：')
print(y)
'''
在位置 1 插入轴之后的数组 y：
[[[1 2]]
            #此空白处就是1插入轴
 [[3 4]]]
'''
print('x.ndim和y.ndim：')
print(x.ndim, y.ndim)
'''
x.ndim 和 y.ndim：
2 3  #x有2个轴，y有3个轴
'''
print('x.shape和y.shape：')
print(x.shape, y.shape)
'''
x.shape和y.shape：
x.shape (2, 2) 
y.shape (2, 1, 2)
'''
print('-----------------------------------------------------')

'''
numpy.squeeze 函数从给定数组的形状中删除一维的条目
numpy.squeeze(arr, axis)
axis：整数或整数元组，用于选择形状中一维条目的子集,维度必须为单维度，否则将会报错
'''
x = np.arange(9).reshape(1,3,3,1)
print('数组x:')
print(x)
'''
数组x:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
'''
#第二个参数可以是整数或整数元组，用于选择形状中一维条目的子集,维度必须为单维度，否则将会报错
#y = np.squeeze(x,0)
#y = np.squeeze(x,3)
#y = np.squeeze(x,1) #报错
y = np.squeeze(x,(0,3))
print('数组y:')
print(y)
'''
[[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print('数组x和y的形状:')
print(x.shape,y.shape)
'''
数组x和y的形状:
x.shape (1, 3, 3)
y.shape (3, 3)
'''

In [ ]:
import numpy as np

'''
numpy.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组
numpy.concatenate((a1, a2, ...), axis)
a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0
'''
a = np.array([[1,2],[3,4]])
print('第一个数组:')
print(a)
b = np.array([[5,6],[7,8]])
print('第二个数组:')
print(b)
# 两个数组的维度相同
print('沿轴0横向连接两个数组:')
print(np.concatenate((a,b)))
print('沿轴1纵向连接两个数组:')
print(np.concatenate((a,b),axis=1))
print('-----------------------------------------------------')
'''
第一个数组:
[[1 2]
 [3 4]]
第二个数组:
[[5 6]
 [7 8]]
沿轴0横向连接两个数组:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
沿轴1纵向连接两个数组:
[[1 2 5 6]
 [3 4 7 8]]
'''

'''
numpy.stack函数用于沿新轴连接数组序列
numpy.stack(arrays, axis)
arrays相同形状的数组序列
axis：返回数组中的轴，输入数组沿着它来堆叠
'''
a = np.array([[1,2],[3,4]])
print('第一个数组:')
print(a)
b = np.array([[5,6],[7,8]])
print('第二个数组:')
print(b)
print('沿轴0堆叠两个数组:')
print(np.stack((a,b),0))
print('沿轴1堆叠两个数组:')
print(np.stack((a,b),1))
print('-----------------------------------------------------')
'''
第一个数组:
[[1 2]
 [3 4]]
第二个数组:
[[5 6]
 [7 8]]
沿轴0堆叠两个数组:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
沿轴1堆叠两个数组:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
'''

#numpy.hstack是numpy.stack函数的变体通过水平堆叠来生成数组
#numpy.vstack是numpy.stack 函数的变体通过垂直堆叠来生成数组
a = np.array([[1,2],[3,4]])
print('第一个数组:')
print(a)
b = np.array([[5,6],[7,8]])
print('第二个数组:')
print(b)
print('水平列堆叠:')
c = np.hstack((a, b))
print(c)
print('竖直行堆叠:')
d = np.vstack((a,b))
print(d)
'''
第一个数组:
[[1 2]
 [3 4]]
第二个数组:
[[5 6]
 [7 8]]
水平列堆叠:
[[1 2 5 6]
 [3 4 7 8]]
竖直行堆叠:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
'''

In [ ]:
import numpy as np

'''
numpy.split 函数沿特定的轴将数组分割为子数组
numpy.split(ary, indices_or_sections, axis)
indices_or_sections：如果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭） 
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
a = np.arange(9)
print('第一个数组：')
print(a)
print('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print(b)
print('将数组在一维数组中表明的位置分割：')
b = np.split(a,[2,4,7])
print(b)
print('-----------------------------------------------------')
'''
第一个数组：
[0 1 2 3 4 5 6 7 8]
将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
将数组在一维数组中表明的位置分割：
[2,4,7]可以理解为:
    2-0            4-2              7-4             剩余
[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])]
'''

#numpy.hsplit函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组
harr = np.floor(100 * np.random.random((2,8))) #生成2X8数组，每个值在100以内
print('原数组:')
print(harr)
print('水平拼接:')
print(np.hsplit(harr,4))
print('-----------------------------------------------------')
'''
原数组:
[[17. 38. 47. 89. 99. 37. 77. 97.]
 [17. 19.  1.  2. 51. 33. 72. 31.]]
拆分后:
[array([[17., 38.],[17., 19.]]), 
 array([[47., 89.],[ 1.,  2.]]), 
 array([[99., 37.],[51., 33.]]), 
 array([[77., 97.],[72., 31.]])]
'''

#numpy.vsplit沿着垂直轴分割，其分割方式与hsplit用法相同
a = np.arange(16).reshape(4,4)
print('第一个数组:')
print(a)
print('竖直拼接:')
b = np.vsplit(a,2)
print(b)
'''
第一个数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
竖直分割:
[array([[0, 1, 2, 3],[4, 5, 6, 7]]), 
 array([[8, 9, 10, 11],[12, 13, 14, 15]])]
'''

In [ ]:
import numpy as np

'''
numpy.resize 函数返回指定大小的新数组
如果新数组大小大于原始大小，则包含原始数组中的元素的副本
numpy.resize(arr, shape)
shape：返回数组的新形状
'''
a = np.array([[1,2,3],[4,5,6]])
print('第一个数组:')
print(a)
print('第一个数组的形状:')
print(a.shape)
b = np.resize(a,(3,2))
print('第二个数组:')
print(b)
print('第二个数组的形状:')
print(b.shape)
# 注意a的第一行在b中重复出现，因为尺寸变大
print('修改第二个数组的大小:')
b = np.resize(a,(3,3))
print(b)
print('-----------------------------------------------------')
'''
第一个数组：
[[1 2 3]
 [4 5 6]]
第一个数组的形状：
(2, 3)
第二个数组：
[[1 2]
 [3 4]
 [5 6]]
第二个数组的形状：
(3, 2)
修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]
'''

'''
numpy.append 函数在数组的末尾添加值。
追加操作会分配整个数组，并把原来的数组复制到新数组中。 此外输入数组的维度必须匹配否则将生成ValueError。
append 函数返回的始终是一个一维数组
numpy.append(arr, values, axis=None)
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！
当axis有定义的时候，分别为0和1的时候。当axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
a = np.array([[1,2,3],[4,5,6]])
print('第一个数组:')
print(a)
print('向数组添加元素:')
print(np.append(a,[7,8,9]))
print('沿轴0添加元素:')
print(np.append(a,[[7,8,9]], axis=0))
print('沿轴1添加元素:')
print(np.append(a,[[5,5,5],[6,6,6]], axis=1))
print('-----------------------------------------------------')
'''
第一个数组:
[[1 2 3]
 [4 5 6]]
向数组添加元素:
[1 2 3 4 5 6 7 8 9]
沿轴0添加元素:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
沿轴1添加元素:
[[1 2 3 5 5 5]
 [4 5 6 6 6 6]]
'''

'''
numpy.insert 函数在给定索引之前，沿给定轴在输入数组中插入值。
numpy.insert(arr, obj, values, axis)
obj：在其之前插入值的索引
values：要插入的值
axis：沿着它插入的轴，如果未提供，则输入数组会被展开
'''
a = np.array([[1,2],[3,4],[5,6]])
print('第一个数组:')
print(a)
print('未传递Axis参数。在插入之前输入数组会被展开。')
print(np.insert(a,3,[11,12]))
print('传递Axis参数。会广播值数组来配输入数组。')
print('沿轴0广播插入第2行:')
print(np.insert(a,1,[11,12],axis=0))
print('沿轴1广播插入第2列:')
print(np.insert(a,1,11,axis=1))
print('-----------------------------------------------------')
'''
第一个数组:
[[1 2]
 [3 4]
 [5 6]]
未传递Axis参数。在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]
传递Axis参数。会广播值数组来配输入数组。
沿轴0广播插入第2行:
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
沿轴1广播插入第2列:
[[ 1 11 2]
 [ 3 11 4]
 [ 5 11 6]]
'''

'''
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。
与insert()函数的情况一样，如果未提供轴参数，则输入数组将展开。
numpy.delete(arr, obj, axis)
'''
a = np.arange(12).reshape(3, 4)
print('第一个数组:')
print(a)
print('未传递Axis参数。在插入之前输入数组会被展开。')
print(np.delete(a, 5))
print('删除第二列:')
print(np.delete(a, 1, axis=1))
print('包含从数组中删除的替代值的切片:')
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a,np.s_[::3]))
print('-----------------------------------------------------')
'''
第一个数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
未传递Axis参数。在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]
删除第二列:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
包含从数组中删除的替代值的切片:
[2 3 5 6 8 9]
'''

'''
numpy.unique 函数用于去除数组中的重复元素
numpy.unique(arr, return_index, return_inverse, return_counts)
return_index：如果为true，返回新列表元素在旧列表中的位置（下标）,并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标）,并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
print('第一个数组:')
print(a)
print('第一个数组的去重值:')
u = np.unique(a)
print(u)
print('新列表元素在旧列表中的位置下标:')
u,indices = np.unique(a, return_index=True)
print(indices)
print('可以看到每个和原数组下标对应的数值:')
print(a)
print('去重数组的下标:')
u,indices = np.unique(a, return_inverse=True)
print(u)
print('旧列表元素在新列表中的位置下标为:')
print(indices)
print('使用下标重构原数组:')
print(u[indices])
print('返回去重元素的重复数量:')
u,indices = np.unique(a, return_counts=True)
print(u)
print(indices)

## 12_ndarrayStr

In [66]:
# numpy.char.add()函数依次对两个数组的元素进行字符串连接
np.char.add(['hello'],['xyz'])

array(['helloxyz'], dtype='<U8')

In [67]:
np.char.add(['hello','hi'], [' abc',' xyz'])

array(['hello abc', 'hi xyz'], dtype='<U9')

In [68]:
#numpy.char.multiply()函数执行多重连接
np.char.multiply('numpy',3)

array('numpynumpynumpy', dtype='<U15')

In [69]:
# numpy.char.center()函数用于将字符串居中，并使用指定字符在左侧和右侧进行填充
# np.char.center(str,width,fillchar)
# width: 长度
# fillchar: 填充字符

np.char.center('numpy',20,fillchar='=')

array('=======numpy========', dtype='<U20')

In [70]:
#numpy.char.capitalize()函数将字符串的第一个字母转换为大写
np.char.title("who's using numpy?")

array("Who'S Using Numpy?", dtype='<U18')

In [71]:
np.char.lower(['BAIDU', 'GOOGLE'])

array(['baidu', 'google'], dtype='<U6')

In [72]:
np.char.lower('BAIDU')

array('baidu', dtype='<U5')

In [74]:
np.char.upper(['baidu', 'google'])

array(['BAIDU', 'GOOGLE'], dtype='<U6')

## 13numpyMath

In [75]:
'''
numpy.around()函数返回指定数字的四舍五入值
numpy.around(a,decimals)
decimals: 舍入的小数位数。默认值为0。如果为负，整数将四舍五入到小数点左侧的位置
'''

import numpy as np

In [76]:
a = np.array([1.0,5.55,123,0.567,25.532])
print('原数组:')
print(a)
print('舍入后:')
print(np.around(a)) #保留整数四舍五入
print(np.around(a,decimals=1)) #保留一位小数四舍五入
print(np.around(a,decimals=-1)) #整数个位数四舍五入

原数组:
[  1.      5.55  123.      0.567  25.532]
舍入后:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [77]:
#numpy.floor()返回小于或者等于指定表达式的最大整数，即向下取整
#numpy.ceil()返回大于或者等于指定表达式的最小整数，即向上取整
a = np.array([-1.7,1.5,-0.2,0.6,10])
print('原数组:')
print(a)
print('修改后floor数组:')
print(np.floor(a))
print('修改后ceil数组:')
print(np.ceil(a))
print('-----------------------------------------------------')


原数组:
[-1.7  1.5 -0.2  0.6 10. ]
修改后floor数组:
[-2.  1. -1.  0. 10.]
修改后ceil数组:
[-1.  2. -0.  1. 10.]
-----------------------------------------------------


In [79]:
a = np.arange(9, dtype=np.float16).reshape(3,3)
print('第一个数组:')
print(a)
print('第二个数组:')
b = np.array([10,10,10])
print(b)
print('两个数组相加:')
print(np.add(a,b))
print('两个数组相减:')
print(np.subtract(a,b))
print('两个数组相乘:')
print(np.multiply(a,b))
print('两个数组相除:')
print(np.divide(a,b))

第一个数组:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
第二个数组:
[10 10 10]
两个数组相加:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
两个数组相减:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
两个数组相乘:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
两个数组相除:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


## 14_ndarrayStat

In [80]:
import numpy as np

In [82]:
# numpy.amin()用于计算数组中的元素沿指定轴的最小值。
# numpy.amax()用于计算数组中的元素沿指定轴的最大值。

a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)
print(np.amin(a,1)) # 横向最小值
print(np.amin(a,0))
print(np.amax(a,1))
print(np.amax(a,0))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
[3 3 2]
[2 4 3]
[7 8 9]
[8 7 9]


In [85]:
#多维数组中指定计算轴
b = np.arange(6).reshape(3,2)
print(b)
wt = np.array([3,5])
print(wt)
# avg = sum(a * weights) / sum(weights)
print(np.average(b,axis=1,weights=wt))
print(np.average(b,axis=1,weights=wt,returned=True))

[[0 1]
 [2 3]
 [4 5]]
[3 5]
[0.625 2.625 4.625]
(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))


## 15_ndarraySort_Filter

In [ ]:
import numpy as np

'''
numpy.sort()函数返回输入数组的排序副本
numpy.sort(a, axis, kind, order)
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段
'''
a = np.array([[3,7],[9,1]])
print('原数组:')
print(a)
print('调用sort() 函数:')
print(np.sort(a))
print('按列排序:')
print(np.sort(a,axis=0))
#在sort函数中排序字段
dt = np.dtype([('name','S10'),('age',int)])
a = np.array([("raju",21), ("anil",25), ("ravi",17), ("amar",27)], dtype=dt)
print('原姓名、年龄数组:')
print(a)
print('按age排序:')
print(np.sort(a,order='age'))
print('-----------------------------------------------------')
'''
原数组:
[[3 7]
 [9 1]]
调用sort() 函数:
[[3 7]
 [1 9]]
按列排序:
[[3 1]
 [9 7]]
姓名、年龄数组:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
按age排序:
[(b'ravi', 17) (b'raju', 21) (b'anil', 25) (b'amar', 27)]
'''

#numpy.argsort()函数返回的是数组值从小到大的索引值
x = np.array([3,1,2])
print('原数组:')
print(x)
print ('对x调用argsort()函数:')
y = np.argsort(x)
print (y)
print ('以排序后的顺序重构原数组:')
print (x[y])
print ('使用循环重构原数组:')
for i in y:print(x[i], end=' ')
print('\n-----------------------------------------------------')
'''
原数组:
[3 1 2]
对 x 调用 argsort() 函数:
[1 2 0] # 排序后的索引值
以排序后的顺序重构原数组:
[1 2 3]
使用循环重构原数组:
1 2 3 
'''

'''
numpy.lexsort() 用于对多个序列进行排序,每一列代表一个序列，排序时优先照顾靠后的列
如重点班录取学生按照总成绩录取。
在总成绩相同时，数学成绩高的优先录取，
在总成绩和数学成绩都相同时，按照英语成绩录取…… 
这里，总成绩排在电子表格的最后一列，数学成绩在倒数第二列，英语成绩在倒数第三列。 
'''
nm = ('raju','anil','ravi','amar')
dv = ('80','90','60','70')
dv1 = ('88','99','66','77')
ind = np.lexsort((dv1,dv,nm))
print('调用lexsort()函数:')
print(ind)
print ('使用这个索引来获取排序后的数据:')
print ([nm[i]+", "+dv[i]+", "+dv1[i] for i in ind])
print('-----------------------------------------------------')
'''
调用 lexsort()函数:
[3 1 0 2]
使用这个索引来获取排序后的数据:
['amar, 70, 77', 'anil, 90, 99', 'raju, 80, 88', 'ravi, 60, 66']
'''

'''
msort(a)数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。 
sort_complex(a)对复数按照先实部后虚部的顺序进行排序 
partition(a, kth[, axis, kind, order])指定一个数，对数组进行分区 
argpartition(a, kth[, axis, kind, order])可以通过关键字 kind 指定算法沿着指定轴对数组进行分区 
'''
print('对复数按照先实部后虚部的顺序进行排序')
print(np.sort_complex([5, 3, 6, 2, 1]))
print(np.sort_complex([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j]))
# [1.+0.j 2.+0.j 3.+0.j 5.+0.j 6.+0.j]
# [1.+2.j 2.-1.j 3.-3.j 3.-2.j 3.+5.j]
print('-----------------------------------------------------')

a = np.array([30, 40, 20, 10])
'''
partition() 分区排序
1.先对数组排序（升序）
2.以排序后的索引是i的元素为基准，将元素分成两部分
3.大于该元素的放在其后面但不排序，小于该元素的放在其前面也不排序
'''
print(np.partition(a,0)) # 以排序后的第1个值10划分 [10 40 20 30]
print(np.partition(a,1)) # 以排序后的第2个值20划分 [10 20 40 30]
print(np.partition(a,2)) # 以排序后的第3个值30划分[10 20 30 40]
print(np.partition(a,3)) # 以排序后的第4个值40划分[20 10 30 40]
print('-----------------------------------------------------')

#argpartition与partition()类似，不过返回的不是分区排序好的元素数组，而是排序完成的元素索引数组
arr = np.array([46, 57, 23, 39, 1, 10, 0, 120])
print('排序后以2为索引基准的前后索引顺序:')
print(np.argpartition(arr,2)) # [6 4 5 3 1 2 0 7]
print(arr[np.argpartition(arr,2)[3]])
print('-----------------------------------------------------')
'''
排序后以2为索引基准的前后索引顺序:
[6 4 5 3 1 2 0 7]
39
*************************************************************
arr[np.argpartition(arr,2)处理过程:
1.[46, 57, 23, 39,  1, 10, 0, 120]的对应索引为
  [0,   1,  2,  3,  4,  5, 6,  7]

2.排序
[0,  1,  10,  23,  39,  46,  57,  120]的对应索引为
[0,  1,   2,   3,   4,   5,   6,   7]

3.通过argpartition对索引2即值10进行小堆前放和大堆后放处理
[0, 1, 10, 39, 57, 23, 46, 120]
[6  4   5   3   1   2   0   7]

4.arr[np.argpartition(arr,2)[3]取出对应索引下标的值
39
*************************************************************
'''
# 同理基准值也可以是多个，如10和23所对应的坐标2,3进行小堆前放和大堆后放处理
print(arr[np.argpartition(arr,[2,3])[2]]) #10
print(arr[np.argpartition(arr,[2,3])[3]]) #23
print('-----------------------------------------------------')

#numpy.argmax()和numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
print('原数组是:')
print(a)
print('调用argmax()函数:')
print(np.argmax(a))
print('展开数组:')
print(a.flatten())
print('沿轴0纵轴的最大值索引:')
maxindex = np.argmax(a,axis=0)
print(maxindex)
print('沿轴1横轴的最大值索引:')
maxindex = np.argmax(a,axis=1)
print(maxindex)
print('调用argmin()函数:')
minindex = np.argmin(a)
print(minindex)
print('展开数组中的最小值:')
print(a.flatten()[minindex])
print('沿轴0纵轴的最小值索引:')
minindex = np.argmin(a,axis=0)
print(minindex)
print('沿轴1横轴的最小值索引:')
minindex = np.argmin(a,axis=1)
print(minindex)
print('-----------------------------------------------------')
'''
原数组是:
[[30 40 70]
 [80 20 10]
 [50 90 60]]
调用argmax()函数:
7  # 90
展开数组:
[30 40 70 80 20 10 50 90 60]
沿轴0纵轴的最大值索引:
[1 2 0]   #80,90,70
沿轴1横轴的最大值索引:
[2 0 1]   #70,80,90
调用argmin()函数:
5 # 10
展开数组中的最小值:
10
沿轴0纵轴的最小值索引:
[0 1 1]   #30,20,10
沿轴1横轴的最小值索引:
[0 2 0]   #30,10,50
'''

#numpy.nonzero()函数返回输入数组中非零元素的索引
a = np.array([[30,40,0],[0,20,10],[50,0,60]])
print('原数组:')
print(a)
print('调用nonzero()函数:')
print(np.nonzero(a))
print('-----------------------------------------------------')
'''
原数组:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
调用nonzero()函数:
(array([0, 0, 1, 1, 2, 2], dtype=int64), 
 array([0, 1, 1, 2, 0, 2], dtype=int64))
'''

#numpy.where()函数返回输入数组中满足给定条件的元素的索引
x = np.arange(9).reshape(3,3)
print('原数组:')
print(x)
print('大于3的元素的索引:')
y = np.where(x>3)
print(y)
print('使用这些索引来获取满足条件的元素:')
print(x[y])
print('-----------------------------------------------------')
'''
原数组:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
大于3的元素的索引:
(array([1, 1, 2, 2, 2], dtype=int64), 
 array([1, 2, 0, 1, 2], dtype=int64))
使用这些索引来获取满足条件的元素:
[4 5 6 7 8]
'''

#numpy.extract()函数根据某个条件从数组中抽取元素，返回满条件的元素
x = np.arange(9).reshape(3,3)
print('原数组:')
print(x)
# 定义条件选择偶数元素
condition = np.mod(x,2)==0
print('按元素的条件值:')
print(condition)
print('使用条件提取元素:')
print(np.extract(condition,x))
'''
原数组:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
按元素的条件值:
[[ True False  True]
 [False  True False]
 [ True False  True]]
使用条件提取元素:
[0 2 4 6 8]
'''

## 16_ndarrayCopy_View

In [ ]:
import numpy as np

'''
无复制 
简单的赋值不会创建数组对象的副本。相反它使用原始数组的相同id()来访问它。 
id()返回Python对象的通用标识符，类似于C中的指针。
'''
a = np.arange(6)
print('原数组:')
print(a)
print('调用id()函数:')
print(id(a))
print('a赋值给b:')
b = a
print(b)
print('b拥有相同id():')
print(id(b))
print('修改b的形状:')
b.shape = 3,2
print(b)
print('a的形状也发生修改:')
print(a)
print('-----------------------------------------------------')
'''
原数组:
[0 1 2 3 4 5]
调用id()函数:
2058598872608
a赋值给b:
[0 1 2 3 4 5]
b拥有相同id():
2058598872608
修改b的形状:
[[0 1]
 [2 3]
 [4 5]]
a的形状也发生修改:
[[0 1]
 [2 3]
 [4 5]]
'''

'''
视图或浅拷贝 
ndarray.view()方会创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数。
'''
a = np.arange(6).reshape(3,2)
print('数组a:')
print(a)
print('创建a的视图:')
b = a.view()
print(b)
print('两个数组的id()不同:')
print('a的id():')
print(id(a))
print('b的id():')
print(id(b))
# 修改b的形状，并不会修改a
b.shape = 2,3
print ('b的形状:')
print (b)
print ('a的形状:')
print (a)
print('-----------------------------------------------------')
'''
数组a:
[[0 1]
 [2 3]
 [4 5]]
创建a的视图:
[[0 1]
 [2 3]
 [4 5]]
两个数组的id()不同:
a的id():
2401323705808
b的id():
2401323419648
b的形状:
[[0 1 2]
 [3 4 5]]
a的形状:
[[0 1]
 [2 3]
 [4 5]]
'''

'''
使用切片创建视图修改数据会影响到原始数组
变量a,b都是arr的一部分视图，对视图的修改会直接反映到原数据中。但是a,b的id不同，视图虽然指向原数据，但是他们和赋值引用还是有区别的。
'''
arr = np.arange(12)
print('原数组:')
print(arr)
print ('创建切片:')
a=arr[3:]
b=arr[3:]
a[1]=123
b[2]=234
print(arr)
print(id(a),id(b),id(arr[3:]))
print('-----------------------------------------------------')
'''
原数组:
[ 0 1 2 3 4 5 6 7 8 9 10 11]
创建切片:
                 a修改 b修改
[0   1   2   3   123   234   6   7   8   9   10   11]
a的id         b的id         arr[3:]的id
2274567028864 2274566338080 2274566338560
'''

'''
副本或深拷贝 
ndarray.copy()函数创建一个副本。对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。
'''
a = np.array([[10,10],[2,3],[4,5]])
print('数组a:')
print(a)
print('创建a的深层副本:')
b = a.copy()
print('数组b:')
print(b)
# b与a不共享任何内容
print('能够通过写入b来写入a吗?')
print (b is a)
print ('修改b的内容:')
b[0,0] = 100
print('修改后的数组b:')
print(b)
print('a保持不变:')
print(a)
print('-----------------------------------------------------')
'''
数组a:
[[10 10]
 [ 2  3]
 [ 4  5]]
创建a的深层副本:
数组b:
[[10 10]
 [ 2  3]
 [ 4  5]]
能够通过写入b来写入a吗?
False
修改b的内容:
修改后的数组b:
[[100  10]
 [  2   3]
 [  4   5]]
a保持不变:
[[10 10]
 [ 2  3]
 [ 4  5]]
'''

## 17_numpy_matlib

In [ ]:
import numpy.matlib
import numpy as np

'''
matlib.empty()函数返回一个新的矩阵
numpy.matlib.empty(shape, dtype, order)
shape: 定义新矩阵形状的整数或整数元组
Dtype: 可选，数据类型
order: C（行序优先） 或者 F（列序优先）
'''
print(np.matlib.empty((2,2))) # 填充为随机数据
print('-----------------------------------------------------')
'''
[[9.90263869e+067 8.01304531e+262]
 [2.60799828e-310 6.01346930e-154]]
'''

#numpy.matlib.zeros()函数创建一个以0填充的矩阵
print(np.matlib.zeros((2,2)))
print('-----------------------------------------------------')
'''
[[0. 0.]
 [0. 0.]]
'''

#numpy.matlib.ones()函数创建一个以1填充的矩阵
print(np.matlib.ones((2,2)))
print('-----------------------------------------------------')
'''
[[1. 1.]
 [1. 1.]]
'''

'''
numpy.matlib.eye()函数返回一个矩阵，对角线元素为1，其他位置为零
numpy.matlib.eye(n, M,k, dtype)
n: 返回矩阵的行数
M: 返回矩阵的列数，默认为 n
k: 对角线的索引
dtype: 数据类型
'''
print(np.matlib.eye(n=3,M=4,k=0,dtype=float))
print('-----------------------------------------------------')
'''
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
'''

'''
numpy.matlib.identity() 函数返回给定大小的单位矩阵
单位矩阵是个方阵，从左上角到右下角的对角线（称为主对角线）上的元素均为1，除此以外全都为0
'''
print(np.matlib.identity(5,dtype=float))
print('-----------------------------------------------------')
'''
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
'''

#numpy.matlib.rand()函数创建一个给定大小的矩阵，数据是随机填充的
print (np.matlib.rand(3,3))
print('-----------------------------------------------------')
'''
[[0.22741839 0.41341901 0.81863817]
 [0.69418085 0.87970331 0.55831519]
 [0.91179528 0.10344144 0.2266316 ]]
'''

i = np.matrix('1,2;3,4')
print('matrix矩阵:')
print(i)
j = np.asarray(i)
print('matrix矩阵转数组:')
print(j)
k = np.asmatrix(j)
print('数组转matrix矩阵:')
print(k)
print('-----------------------------------------------------')
'''
matrix矩阵:
[[1 2]
 [3 4]]
matrix矩阵转数组:
[[1 2]
 [3 4]]
数组转matrix矩阵:
[[1 2]
 [3 4]]
'''

## 18_numpy_linalg

In [ ]:
# 线性代数
import numpy.matlib
import numpy as np

'''
两个数组的点积，即元素对应相乘
numpy.dot(a, b, out=None) 
a : ndarray 数组 
b : ndarray 数组 
out : ndarray, 可选用来保存dot()的计算结果
numpy.dot()对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
对于二维数组，计算的是两个数组的矩阵乘积；
对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：
数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和： 
dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])。
'''
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a, b))
print('-----------------------------------------------------')
'''
dot
（[[1,2]      [[11,12]
   [3,4]]      [13,14]]）
=
[[37 40]
 [85 92]]
 计算方法:[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
'''

'''
两个向量的点积
numpy.vdot()函数是两个向量的点积。如果第一个参数是复数，那么它的共轭复数会用于计算。
(共轭复数，两个实部相等，虚部互为相反数的复数互为共轭复数)
如果参数是多维数组，它会被展开。
'''
a = np.array([[1,2], [3,4]])
b = np.array([[11,12], [13,14]])
# vdot将数组展开计算内积
print(np.vdot(a,b))
print('-----------------------------------------------------')
'''
130
1*11 + 2*12 + 3*13 + 4*14 = 130
'''

'''
两个数组的内积 
numpy.inner()函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。
'''
print(np.inner(np.array([1,2,3]),np.array([0,1,0])))
print('-----------------------------------------------------')
'''
2
1*0+2*1+3*0
'''

# 多维数组
a = np.array([[1,2], [3,4]])
print('数组a:')
print(a)
b = np.array([[11,12], [13,14]])
print('数组b:')
print(b)
print('内积:')
print(np.inner(a, b))
print('-----------------------------------------------------')
'''
数组a:
[[1 2]
 [3 4]]
数组b:
[[11 12]
 [13 14]]
内积:
[[35 41]
 [81 95]]
1*11+2*12, 1*13+2*14 
3*11+4*12, 3*13+4*14
'''

'''
两个数组的矩阵积 
numpy.matmul函数返回两个数组的矩阵乘积。
虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。
另一方面，如果任一参数是一维数组，则通过在其维度上附加1来将其提升为矩阵，并在乘法之后被去除。
'''
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
print(np.matmul(a,b))
print('-----------------------------------------------------')
'''
[[4 1]
 [2 2]]
'''
#二维和一维运算
a = [[1,0],[0,1]]
b = [1,2]
print(np.matmul(a,b))
print(np.matmul(b,a))
print('-----------------------------------------------------')
'''
[1 2]
[1 2]
'''
#维度大于二的数组
a = np.arange(8).reshape(2,2,2)
b = np.arange(4).reshape(2,2)
print(np.matmul(a,b))
print('-----------------------------------------------------')
'''
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]
'''

'''
数组的行列式 
numpy.linalg.det() 函数计算输入矩阵的行列式。
行列式在线性代数中是非常有用的值。 它从方阵的对角元素计算。 对于 2×2 矩阵，它是左上和右下元素的乘积与其他两个的乘积的差。
对于矩阵[[a，b]，[c，d]]，行列式计算为 ad-bc。 较大的方阵被认为是 2×2 矩阵的组合。
'''
a = np.array([[1,2], [3,4]])
print(np.linalg.det(a))
print('-----------------------------------------------------')
# -2.0

b = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(b)
print(np.linalg.det(b))
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))
print('-----------------------------------------------------')
'''
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306
'''

'''
求解线性矩阵方程(求解多元一次方程组)
numpy.linalg.solve()函数给出了矩阵形式的线性方程的解
列1:
x + y + z = 6
2y + 5z = -4
2x + 5y - z = 27
解题：
solve函数有两个参数a和b。
a是一个N*N的二维数组，而b是一个长度为N的一维数组，
solve函数找到一个长度为N的一维数组x，
使得a和x的矩阵乘积正好等于b，数组x就是多元一次方程组的解。
'''
a = np.random.rand(10,10)
b = np.random.rand(10)
x = np.linalg.solve(a,b)
result=np.sum(np.abs(np.dot(a,x) - b))
print(result)
print('-----------------------------------------------------')
# 1.0547118733938987e-15

'''
计算矩阵的乘法逆矩阵
numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。
逆矩阵（inverse matrix）：设A是数域上的一个n阶矩阵，若在相同数域上存在另一个n阶矩阵B，
使得： AB=BA=E ，则称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。
'''
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y)) #两个数组的点积
print('-----------------------------------------------------')
'''
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
'''

#创建矩阵A的逆矩阵
a = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
print('数组a:')
print(a)
ainv = np.linalg.inv(a)
print('a的逆:')
print(ainv)
print('矩阵b:')
b = np.array([[6],[-4],[27]])
print(b)
print('计算A^(-1)B:')
x = np.linalg.solve(a,b) # 等同于np.dot(ainv,b)
print(x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解
'''
数组a:
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆:
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵b:
[[ 6]
 [-4]
 [27]]
计算A^(-1)B:
[[ 5.]
 [ 3.]
 [-2.]]
'''






## 19_numpy_io

In [ ]:
import numpy as np

'''
numpy.save()函数将数组保存到以.npy为扩展名的文件中
numpy.save(file, arr, allow_pickle=True, fix_imports=True)
file：要保存的文件，扩展名为 .npy，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上。
arr: 要保存的数组
allow_pickle: 可选布尔值，允许使用 Python pickles 保存对象数组，
Python 中的pickle用于在保存到磁盘文件或从磁盘文件读取之前，对对象进行序列化和反序列化。
fix_imports: 可选为了方便Pyhton2中读取 Python3保存的数据。
'''
a = np.array([1,2,3,4,5])
# 保存到 outfile.npy 文件上
np.save('outfile.npy', a)
# 保存到 outfile2.npy 文件上，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上
np.save('outfile2', a)
b = np.load('outfile.npy')
print(b)
print('-----------------------------------------------------')
'''
[1 2 3 4 5]
直接查看文件是乱码，是Numpy专用的二进制格式后的数据:
�NUMPY v {'descr': '<i4', 'fortran_order': False, 'shape': (5,), }
'''

'''
numpy.savez()函数将多个数组保存到以npz为扩展名的文件中。
numpy.savez(file, *args, **kwds)
file：要保存的文件，扩展名为 .npz，如果文件路径末尾没有扩展名 .npz，该扩展名会被自动加上。
args: 要保存的数组，可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名为 arr_0, arr_1, …　。
kwds: 要保存的数组使用关键字名称。
'''
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
# c使用了自定义数组名称
np.savez("mynpz.npz", a, b, c_title=c)
r = np.load("mynpz.npz")
print(r.files) # 查看各个数组名称
print(r["arr_0"]) # 数组a
print(r["arr_1"]) # 数组b
print(r["c_title"]) # 数组c
print('-----------------------------------------------------')
'''
['c_title', 'arr_0', 'arr_1']
[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
'''

'''
savetxt()函数是以简单的文本文件格式存储数据，对应的使用loadtxt()函数来获取数据。
np.loadtxt(FILENAME, dtype=int, delimiter=' ')
np.savetxt(FILENAME, a, fmt="%d", delimiter=",")
参数delimiter可以指定各种分隔符、针对特定列的转换器函数、需要跳过的行数等。
'''
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)
print('-----------------------------------------------------')
#[1. 2. 3. 4. 5.]

#使用delimiter参数
#reshape某个维度等于-1的话，那么Numpy会根据剩下的维度计算出数组的另外一个shape属性值
a=np.arange(0,10,0.5).reshape(4,-1)
print("a原数组:")
print(a)
np.savetxt("out.txt",a,fmt="%d",delimiter=",") # 改为保存为整数，以逗号分隔
b = np.loadtxt("out.txt",delimiter=",") # load 时也要指定为逗号分隔
print(b)
'''
a原数组:
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
[[0. 0. 1. 1. 2.]
 [2. 3. 3. 4. 4.]
 [5. 5. 6. 6. 7.]
 [7. 8. 8. 9. 9.]]

out.txt文件:
0,0,1,1,2
2,3,3,4,4
5,5,6,6,7
7,8,8,9,9
'''

## 20_numpy_matplotlib

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import matplotlib

x = np.arange(2,11)
print('x矩阵:')
print(x)
print('y矩阵:')
y = 2 * x + 5
print(y)
print('生成matplot')
plt.title("Matplotlib demo")
plt.xlabel("x axis caption")
plt.ylabel("y axis caption")
plt.plot(x,y)
plt.show()
print('-----------------------------------------------------')
'''
x矩阵:
[ 2  3  4  5  6  7  8  9 10]
y矩阵:
[ 9 11 13 15 17 19 21 23 25]
生成matplot
'''

'''
图形中文显示
Matplotlib 默认情况不支持中文，将simhei.ttf文件放在当前执行的代码文件中
'''
zhfont = matplotlib.font_manager.FontProperties(fname="simhei.ttf")
x = np.arange(2, 11)
y = 2 * x + 5
plt.title("中文标题", fontproperties=zhfont)
# fontproperties 设置中文显示，fontsize 设置字体大小
plt.xlabel("x 轴", fontproperties=zhfont)
plt.ylabel("y 轴", fontproperties=zhfont)
plt.plot(x,y)
plt.show()
print('-----------------------------------------------------')
'''
x矩阵:
[ 2  3  4  5  6  7  8  9 10]
y矩阵:
[ 9 11 13 15 17 19 21 23 25]
生成matplot
'''

# 显示已安装的系统字体
a=sorted([f.name for f in matplotlib.font_manager.fontManager.ttflist])
for i in a:print(i)
print('-----------------------------------------------------')

# 点线图
x = np.arange(2,11)
y =  2  * x +  5
plt.title("Matplotlib demo")
plt.xlabel("x axis caption")
plt.ylabel("y axis caption")
plt.plot(x,y,"ob")
plt.show()
print('-----------------------------------------------------')

# 正弦波
# 计算正弦曲线上点的 x 和 y 坐标
x = np.arange(0,3*np.pi,0.1)
y = np.sin(x)
plt.title("sine wave form")
plt.plot(x, y)
plt.show()
print('-----------------------------------------------------')

#subplot()绘制正弦和余弦值
# 计算正弦和余弦曲线上的点的 x 和 y 坐标
x = np.arange(0,3* np.pi,0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
# 建立 subplot 网格，高为 2，宽为 1
# 激活第一个 subplot
plt.subplot(2,1,1)
# 绘制第一个图像
plt.plot(x, y_sin)
plt.title('Sin')
# 将第二个 subplot 激活，并绘制第二个图像
plt.subplot(2,1,2)
plt.plot(x, y_cos)
plt.title('Cos')
# 展示图像
plt.show()
print('-----------------------------------------------------')

#pyplot子模块提供bar()函数来生成条形图
x = [5,8,10]
y = [12,16,6]
x2 = [6,9,11]
y2 = [6,15,7]
plt.bar(x,y,align='center')
plt.bar(x2,y2,color='gray',align='center')
plt.title('Bar graph')
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()
print('-----------------------------------------------------')

'''
numpy.histogram()函数是数据的频率分布的图形表示。 水平尺寸相等的矩形对应于类间隔，称为bin，变量height对应于频率。
numpy.histogram()函数将输入数组和bin作为两个参数。 bin数组中的连续元素用作每个bin的边界。
'''
#histogram图例1
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27])
plt.hist(a,bins=[0,20,40,60,80,100])
plt.title("histogram")
plt.show()
print('-----------------------------------------------------')

#histogram图例2
#生成一些随机数
rng=np.random.RandomState(10) #使用RandomState获得随机数生成器
data1=rng.normal(size=50)
data2=rng.normal(size=100)
binrange=[-1,0,2] # 设置区间, 分别是[-1,0]和[0,2]
hist1,_ = np.histogram(data1, bins=binrange)
hist2,_ = np.histogram(data2, bins=binrange)
# 绘制图像
fig, ax1 = plt.subplots()
fig.set_size_inches(10, 6)
# plt.set_cmap('RdBu') #set_cmap()方法更改现有的绘图对象的色图
x = np.arange(len(binrange)-1)*3
w=0.3
# 绘制多个bar在同一个图中, 这里需要控制width
plt.bar(x-w,hist1,width=2*w,align='center')
plt.bar(x+w,hist2,width=2*w,align='center')
# 设置坐标轴的标签
ax1.yaxis.set_tick_params(labelsize=15) # 设置y轴的字体的大小
ax1.set_xticks(x) # 设置xticks出现的位置
# 设置坐标轴名称
ax1.set_ylabel("Count", fontsize='xx-large')
# 设置标题
ax1.set_title('The Distribution of Normal1 Data and Normal2 Data', fontsize='x-large')
# 设置图例
plt.legend(('Normal1','Nomral2'),fontsize = 'x-large', loc='upper right')
plt.show()
print('-----------------------------------------------------')