In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# 生成3层嵌套数组
c = np.array([1,2,3,4,5],ndmin=3)
print(c)

[[[1 2 3 4 5]]]


In [5]:
# 设置dtype数组元素的数据类型
d = np.array([[1,2,3],[1.23,2.34,4.56]],dtype=np.float64)
d

array([[1.  , 2.  , 3.  ],
       [1.23, 2.34, 4.56]])